# Docs ref: https://docs.codecov.io/docs/codecovyml-reference
# Validation check: $ curl --data-binary @codecov.yml https://codecov.io/validate

codecov:
  bot: "codecov-io"
  strict_yaml_branch: "yaml-config"
  require_ci_to_pass: yes
  notify:
    wait_for_ci: yes

coverage:
  precision: 2
  round: down
  range: "85...100"
  status:
    project:
      default:
        base: auto # target to compare against
        target: auto # target "X%" coverage to hit on project
        threshold: 0.5% # allow this much decrease from base
        if_ci_failed: error
    patch:
      default:
        base: auto # target to compare against
        target: 50% # target "X%" coverage to hit on patch
        # threshold: 50%  # allow this much decrease on patch
    changes: false

parsers:
  gcov:
    branch_detection:
      conditional: yes
      loop: yes
      method: no
      macro: no

# https://docs.codecov.io/docs/pull-request-comments
comment:
  layout: header, diff, sunburst, uncovered
  behavior: default
  require_changes: false # if true: only post the comment if coverage changes

ignore:
  # Distributed files (require torchrun/multi-GPU, not available in CI)
  - "torchdr/distributed/__init__.py"
  - "torchdr/cli.py"  # CLI for distributed execution
  # Files with mixed FAISS/distributed code paths (partial coverage expected)
  - "torchdr/distance/base.py"  # FAISS + distributed code paths
  - "torchdr/affinity/base.py"  # FAISS + DataLoader + distributed code paths
  - "torchdr/neighbor_embedding/base.py"  # distributed code paths
  - "torchdr/spectral_embedding/incremental_pca.py"  # distributed PCA
  - "torchdr/affinity_matcher.py"  # DataLoader paths
  - "torchdr/utils/wrappers.py"  # wrapper utilities with DataLoader support
  # Test files should not count toward coverage
  - "torchdr/tests/**"
