name: Testing
on:
  workflow_dispatch:
  pull_request:
    branches:
      - "main"
  push:
    branches:
      - "main"
  create:
    branches:
      - "main"
    tags:
      - "**"

jobs:
  Test:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
    defaults:
      run:
        shell: bash -l {0}
    steps:
      # Install torchdr
      - name: Checking Out Repository
        uses: actions/checkout@v2
      # Cache 'torchdr' datasets
      - name: Create/Restore torchdr Data Cache
        id: cache-torchdr_datasets
        uses: actions/cache@v2
        with:
          path: ~/torchdr_datasets
          key: ${{ runner.os }}-v3
      # Install Python & Packages
      - uses: actions/setup-python@v4
        with:
          python-version: "3.10"
      - run: which python
      - name: Install dependencies
        run: |
          python -m pip install --user --upgrade --progress-bar off pip
      - name: Install 'torchdr' package
        run: |
          python -m pip install --user -e .[all,test]
      # Run Tests
      - name: Run Tests
        run: pytest torchdr/ --verbose --cov=torchdr torchdr/ --cov-report term
      # Codecov
      - name: Upload coverage reports to Codecov
        uses: codecov/codecov-action@v4.0.1
        with:
          token: ${{ secrets.CODECOV_TOKEN }}
          slug: TorchDR/TorchDR

  Test-minimal:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
    defaults:
      run:
        shell: bash -l {0}
    steps:
      # Install torchdr
      - name: Checking Out Repository
        uses: actions/checkout@v2
      # Cache 'torchdr' datasets
      - name: Create/Restore torchdr Data Cache
        id: cache-torchdr_datasets
        uses: actions/cache@v2
        with:
          path: ~/torchdr_datasets
          key: ${{ runner.os }}-v3
      # Install Python & Packages
      - uses: actions/setup-python@v4
        with:
          python-version: "3.10"
      - run: which python
      - name: Install dependencies
        run: |
          python -m pip install --user --upgrade --progress-bar off pip
      - name: Install 'torchdr' package
        run: |
          python -m pip install --user -e .[test]
      # Run Tests
      - name: Run Tests
        run: pytest torchdr/ --verbose --cov=torchdr torchdr/ --cov-report term
      # Codecov
      - name: Upload coverage reports to Codecov
        uses: codecov/codecov-action@v4.0.1
        with:
          token: ${{ secrets.CODECOV_TOKEN }}
          slug: TorchDR/TorchDR

  Test-faiss:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
    defaults:
      run:
        shell: bash -l {0}
    steps:
      - name: Checking Out Repository
        uses: actions/checkout@v2
      - name: Create/Restore torchdr Data Cache
        id: cache-torchdr_datasets_faiss
        uses: actions/cache@v2
        with:
          path: ~/torchdr_datasets
          key: ${{ runner.os }}-v3-faiss
      - name: Set up Miniconda
        uses: conda-incubator/setup-miniconda@v2
        with:
          auto-update-conda: true
          python-version: "3.10"
          activate-environment: test-faiss-env
      - run: which python
      - name: Upgrade pip
        run: pip install --upgrade pip
      - name: Install FAISS
        run: conda install -c conda-forge -c pytorch faiss-cpu=1.10.0 --yes
      - name: Install 'torchdr' package
        run: pip install -e ".[test]"
      - name: Run Tests
        run: pytest torchdr/tests/test_utils.py --verbose --cov=torchdr torchdr/ --cov-report term
      - name: Upload coverage reports to Codecov
        uses: codecov/codecov-action@v4.0.1
        with:
          token: ${{ secrets.CODECOV_TOKEN }}
          slug: TorchDR/TorchDR
